-- Stable, serializable error envelopes used by server and client contracts.
PortOps = PortOps or {}
PortOps.Errors = PortOps.Errors or {}

local Errors = PortOps.Errors

Errors.codes = {
    CONFIG_INVALID = 'CONFIG_INVALID',
    RESOURCE_NOT_READY = 'RESOURCE_NOT_READY',
    DATABASE_NOT_READY = 'DATABASE_NOT_READY',
    DATABASE_DRIVER_UNAVAILABLE = 'DATABASE_DRIVER_UNAVAILABLE',
    DATABASE_PROVIDER_UNSUPPORTED = 'DATABASE_PROVIDER_UNSUPPORTED',
    MIGRATION_FAILED = 'MIGRATION_FAILED',
    MIGRATION_CONFIG_INVALID = 'MIGRATION_CONFIG_INVALID',
    SCHEMA_VERSION_UNSUPPORTED = 'SCHEMA_VERSION_UNSUPPORTED',
    FRAMEWORK_PROVIDER_UNSUPPORTED = 'FRAMEWORK_PROVIDER_UNSUPPORTED',
    FRAMEWORK_PROVIDER_UNAVAILABLE = 'FRAMEWORK_PROVIDER_UNAVAILABLE',
    FRAMEWORK_IDENTITY_UNAVAILABLE = 'FRAMEWORK_IDENTITY_UNAVAILABLE',
    FRAMEWORK_ADAPTER_INVALID = 'FRAMEWORK_ADAPTER_INVALID',
    CRANE_NOT_FOUND = 'CRANE_NOT_FOUND',
    CRANE_OCCUPIED = 'CRANE_OCCUPIED',
    CRANE_UNAVAILABLE = 'CRANE_UNAVAILABLE',
    SESSION_INVALID = 'SESSION_INVALID',
    SESSION_OWNER_MISMATCH = 'SESSION_OWNER_MISMATCH',
    SNAPSHOT_INVALID = 'SNAPSHOT_INVALID',
    SNAPSHOT_STALE = 'SNAPSHOT_STALE',
    SNAPSHOT_RATE_LIMITED = 'SNAPSHOT_RATE_LIMITED',
    SNAPSHOT_OUT_OF_BOUNDS = 'SNAPSHOT_OUT_OF_BOUNDS',
    SNAPSHOT_DELTA_TOO_LARGE = 'SNAPSHOT_DELTA_TOO_LARGE',
    SNAPSHOT_TIMESTAMP_INVALID = 'SNAPSHOT_TIMESTAMP_INVALID',
    TOKEN_INVALID = 'TOKEN_INVALID',
    TOKEN_RATE_LIMITED = 'TOKEN_RATE_LIMITED',
    TOKEN_EXPIRED = 'TOKEN_EXPIRED',
    TOKEN_REPLAY = 'TOKEN_REPLAY',
    TOKEN_BINDING_MISMATCH = 'TOKEN_BINDING_MISMATCH',
    RECOVERY_REQUIRED = 'RECOVERY_REQUIRED',
    CONTAINER_INVALID = 'CONTAINER_INVALID',
    CONTAINER_NOT_FOUND = 'CONTAINER_NOT_FOUND',
    CONTAINER_ID_EXISTS = 'CONTAINER_ID_EXISTS',
    CONTAINER_NUMBER_EXISTS = 'CONTAINER_NUMBER_EXISTS',
    CONTAINER_REPOSITORY_FAILED = 'CONTAINER_REPOSITORY_FAILED',
    CONTAINER_VERSION_INVALID = 'CONTAINER_VERSION_INVALID',
    CONTAINER_VERSION_CONFLICT = 'CONTAINER_VERSION_CONFLICT',
    CONTAINER_TRANSITION_INVALID = 'CONTAINER_TRANSITION_INVALID',
    CONTAINER_GUARD_REJECTED = 'CONTAINER_GUARD_REJECTED',
    STREAM_POSITION_INVALID = 'STREAM_POSITION_INVALID',
    STREAMING_UNAVAILABLE = 'STREAMING_UNAVAILABLE',
    STREAM_RATE_LIMITED = 'STREAM_RATE_LIMITED',
    STREAM_DESCRIPTOR_INVALID = 'STREAM_DESCRIPTOR_INVALID',
    STREAM_STALE_RESPONSE = 'STREAM_STALE_RESPONSE',
    INPUT_INVALID = 'INPUT_INVALID',
    NOT_AUTHORIZED = 'NOT_AUTHORIZED',
    YARD_CONFIG_INVALID = 'YARD_CONFIG_INVALID', SLOT_NOT_FOUND = 'SLOT_NOT_FOUND', SLOT_RESERVED = 'SLOT_RESERVED',
    SLOT_UNAVAILABLE = 'SLOT_UNAVAILABLE', SLOT_VERSION_CONFLICT = 'SLOT_VERSION_CONFLICT', SLOT_OCCUPANT_INVALID = 'SLOT_OCCUPANT_INVALID',
    RESERVATION_INVALID = 'RESERVATION_INVALID', RESERVATION_NOT_FOUND = 'RESERVATION_NOT_FOUND', RESERVATION_EXPIRED = 'RESERVATION_EXPIRED',
    RESERVATION_OWNER_INVALID = 'RESERVATION_OWNER_INVALID', ISO_INCOMPATIBLE = 'ISO_INCOMPATIBLE', ZONE_INCOMPATIBLE = 'ZONE_INCOMPATIBLE',
    SNAP_INVALID = 'SNAP_INVALID', SNAP_OUT_OF_TOLERANCE = 'SNAP_OUT_OF_TOLERANCE', YARD_UNAVAILABLE = 'YARD_UNAVAILABLE',
    MOVE_INVALID = 'MOVE_INVALID', MOVE_NOT_FOUND = 'MOVE_NOT_FOUND', MOVE_TRANSITION_INVALID = 'MOVE_TRANSITION_INVALID',
    MOVE_GUARD_REJECTED = 'MOVE_GUARD_REJECTED', MOVE_VERSION_INVALID = 'MOVE_VERSION_INVALID', MOVE_VERSION_CONFLICT = 'MOVE_VERSION_CONFLICT',
    MOVE_STEP_INVALID = 'MOVE_STEP_INVALID', MOVE_STEP_NOT_FOUND = 'MOVE_STEP_NOT_FOUND', MOVE_STEP_TRANSITION_INVALID = 'MOVE_STEP_TRANSITION_INVALID',
    MOVE_PREREQUISITE_REQUIRED = 'MOVE_PREREQUISITE_REQUIRED', MOVE_CONTAINER_SYNC_FAILED = 'MOVE_CONTAINER_SYNC_FAILED',
    ASSIGNMENT_NOT_AUTHORIZED = 'ASSIGNMENT_NOT_AUTHORIZED', ASSIGNMENT_REASON_REQUIRED = 'ASSIGNMENT_REASON_REQUIRED', ASSIGNMENT_UNAVAILABLE = 'ASSIGNMENT_UNAVAILABLE',
    API_UNAVAILABLE = 'API_UNAVAILABLE', API_FAILED = 'API_FAILED', API_NOT_FOUND = 'API_NOT_FOUND',
    IDEMPOTENCY_INVALID = 'IDEMPOTENCY_INVALID', IDEMPOTENCY_KEY_REQUIRED = 'IDEMPOTENCY_KEY_REQUIRED', IDEMPOTENCY_IN_PROGRESS = 'IDEMPOTENCY_IN_PROGRESS',
    IDEMPOTENCY_STORAGE_FAILED = 'IDEMPOTENCY_STORAGE_FAILED', IDEMPOTENCY_STORAGE_INVALID = 'IDEMPOTENCY_STORAGE_INVALID',
    IDEMPOTENCY_STORAGE_UNAVAILABLE = 'IDEMPOTENCY_STORAGE_UNAVAILABLE', IDEMPOTENCY_OPERATION_INVALID = 'IDEMPOTENCY_OPERATION_INVALID',
    VESSEL_INVALID = 'VESSEL_INVALID', VESSEL_NOT_FOUND = 'VESSEL_NOT_FOUND', VESSEL_EXISTS = 'VESSEL_EXISTS',
    VESSEL_CALL_INVALID = 'VESSEL_CALL_INVALID', VESSEL_CALL_NOT_FOUND = 'VESSEL_CALL_NOT_FOUND', VESSEL_CALL_EXISTS = 'VESSEL_CALL_EXISTS',
    BERTH_CONFLICT = 'BERTH_CONFLICT', BERTH_NOT_FOUND = 'BERTH_NOT_FOUND', BERTH_INCOMPATIBLE = 'BERTH_INCOMPATIBLE', BERTH_CRANE_UNAVAILABLE = 'BERTH_CRANE_UNAVAILABLE',
    MANIFEST_INVALID = 'MANIFEST_INVALID', MANIFEST_NOT_FOUND = 'MANIFEST_NOT_FOUND', MANIFEST_EXISTS = 'MANIFEST_EXISTS', MANIFEST_DUPLICATE = 'MANIFEST_DUPLICATE',
    YARD_CAPACITY_UNAVAILABLE = 'YARD_CAPACITY_UNAVAILABLE', APPOINTMENT_INVALID = 'APPOINTMENT_INVALID', APPOINTMENT_NOT_FOUND = 'APPOINTMENT_NOT_FOUND',
    APPOINTMENT_EXISTS = 'APPOINTMENT_EXISTS', APPOINTMENT_TRANSITION_INVALID = 'APPOINTMENT_TRANSITION_INVALID', APPOINTMENT_VERSION_CONFLICT = 'APPOINTMENT_VERSION_CONFLICT',
    APPOINTMENT_CONTAINER_MISMATCH = 'APPOINTMENT_CONTAINER_MISMATCH', APPOINTMENT_OUTSIDE_WINDOW = 'APPOINTMENT_OUTSIDE_WINDOW', APPOINTMENT_WINDOW_ACTIVE = 'APPOINTMENT_WINDOW_ACTIVE',
    CUSTOMS_HOLD = 'CUSTOMS_HOLD', CONTAINER_NOT_READY = 'CONTAINER_NOT_READY', EMPLOYEE_NOT_CERTIFIED = 'EMPLOYEE_NOT_CERTIFIED',
    RECOVERY_INVALID = 'RECOVERY_INVALID', ANALYTICS_RANGE_INVALID = 'ANALYTICS_RANGE_INVALID',
    FIELD_OPERATION_INVALID = 'FIELD_OPERATION_INVALID', FIELD_OPERATION_UNAVAILABLE = 'FIELD_OPERATION_UNAVAILABLE', FIELD_OPERATION_CONTAINER_MISMATCH = 'FIELD_OPERATION_CONTAINER_MISMATCH'
}

local function envelope(ok, data, code, message, details)
    return {
        ok = ok,
        data = data,
        error = ok and nil or {
            code = code,
            message = message,
            details = details
        }
    }
end
function Errors.ok(data, meta)
    local result = envelope(true, data)
    result.meta = meta
    return result
end

function Errors.err(code, message, details)
    return envelope(false, nil, code, message or code, details)
end

function Errors.isOk(result)
    return type(result) == 'table' and result.ok == true
end

function Errors.code(reason, fallback)
    if type(reason) == 'table' and reason.error then return reason.error.code end
    if type(reason) == 'string' and Errors.codes[reason] then return reason end
    return fallback or Errors.codes.INPUT_INVALID
end
