-- Stable, serializable error envelopes used by server and client contracts.
PortOps = PortOps or {}
PortOps.Errors = PortOps.Errors or {}

local Errors = PortOps.Errors

Errors.codes = {
    CONFIG_INVALID = 'CONFIG_INVALID',
    RESOURCE_NOT_READY = 'RESOURCE_NOT_READY',
    DATABASE_NOT_READY = 'DATABASE_NOT_READY',
    DATABASE_DRIVER_UNAVAILABLE = 'DATABASE_DRIVER_UNAVAILABLE',
    DATABASE_PROVIDER_UNSUPPORTED = 'DATABASE_PROVIDER_UNSUPPORTED',
    MIGRATION_FAILED = 'MIGRATION_FAILED',
    MIGRATION_CONFIG_INVALID = 'MIGRATION_CONFIG_INVALID',
    SCHEMA_VERSION_UNSUPPORTED = 'SCHEMA_VERSION_UNSUPPORTED',
    FRAMEWORK_PROVIDER_UNSUPPORTED = 'FRAMEWORK_PROVIDER_UNSUPPORTED',
    FRAMEWORK_PROVIDER_UNAVAILABLE = 'FRAMEWORK_PROVIDER_UNAVAILABLE',
    FRAMEWORK_IDENTITY_UNAVAILABLE = 'FRAMEWORK_IDENTITY_UNAVAILABLE',
    FRAMEWORK_ADAPTER_INVALID = 'FRAMEWORK_ADAPTER_INVALID',
    CRANE_NOT_FOUND = 'CRANE_NOT_FOUND',
    CRANE_OCCUPIED = 'CRANE_OCCUPIED',
    CRANE_UNAVAILABLE = 'CRANE_UNAVAILABLE',
    SESSION_INVALID = 'SESSION_INVALID',
    SESSION_OWNER_MISMATCH = 'SESSION_OWNER_MISMATCH',
    SNAPSHOT_INVALID = 'SNAPSHOT_INVALID',
    SNAPSHOT_STALE = 'SNAPSHOT_STALE',
    SNAPSHOT_RATE_LIMITED = 'SNAPSHOT_RATE_LIMITED',
    SNAPSHOT_OUT_OF_BOUNDS = 'SNAPSHOT_OUT_OF_BOUNDS',
    SNAPSHOT_DELTA_TOO_LARGE = 'SNAPSHOT_DELTA_TOO_LARGE',
    SNAPSHOT_TIMESTAMP_INVALID = 'SNAPSHOT_TIMESTAMP_INVALID',
    TOKEN_INVALID = 'TOKEN_INVALID',
    TOKEN_RATE_LIMITED = 'TOKEN_RATE_LIMITED',
    TOKEN_EXPIRED = 'TOKEN_EXPIRED',
    TOKEN_REPLAY = 'TOKEN_REPLAY',
    TOKEN_BINDING_MISMATCH = 'TOKEN_BINDING_MISMATCH',
    RECOVERY_REQUIRED = 'RECOVERY_REQUIRED',
    CONTAINER_INVALID = 'CONTAINER_INVALID',
    CONTAINER_NOT_FOUND = 'CONTAINER_NOT_FOUND',
    CONTAINER_ID_EXISTS = 'CONTAINER_ID_EXISTS',
    CONTAINER_NUMBER_EXISTS = 'CONTAINER_NUMBER_EXISTS',
    CONTAINER_REPOSITORY_FAILED = 'CONTAINER_REPOSITORY_FAILED',
    CONTAINER_VERSION_INVALID = 'CONTAINER_VERSION_INVALID',
    CONTAINER_VERSION_CONFLICT = 'CONTAINER_VERSION_CONFLICT',
    CONTAINER_TRANSITION_INVALID = 'CONTAINER_TRANSITION_INVALID',
    CONTAINER_GUARD_REJECTED = 'CONTAINER_GUARD_REJECTED',
    STREAM_POSITION_INVALID = 'STREAM_POSITION_INVALID',
    STREAMING_UNAVAILABLE = 'STREAMING_UNAVAILABLE',
    STREAM_RATE_LIMITED = 'STREAM_RATE_LIMITED',
    STREAM_DESCRIPTOR_INVALID = 'STREAM_DESCRIPTOR_INVALID',
    STREAM_STALE_RESPONSE = 'STREAM_STALE_RESPONSE',
    INPUT_INVALID = 'INPUT_INVALID',
    NOT_AUTHORIZED = 'NOT_AUTHORIZED'
}

local function envelope(ok, data, code, message, details)
    return {
        ok = ok,
        data = data,
        error = ok and nil or {
            code = code,
            message = message,
            details = details
        }
    }
end
function Errors.ok(data, meta)
    local result = envelope(true, data)
    result.meta = meta
    return result
end

function Errors.err(code, message, details)
    return envelope(false, nil, code, message or code, details)
end

function Errors.isOk(result)
    return type(result) == 'table' and result.ok == true
end

function Errors.code(reason, fallback)
    if type(reason) == 'table' and reason.error then return reason.error.code end
    if type(reason) == 'string' and Errors.codes[reason] then return reason end
    return fallback or Errors.codes.INPUT_INVALID
end
